import "./customEvents.js";
import "./utils.js";
import "./politic.js";
import "./agree.js";
import "./forms.js";
import "./modals.js";
import "./last-day.js";
import "./masks.js";
import "./htmlHelper.js";